#defaultBaseImage: gcr.io/distroless/static:debug

defaultPlatforms:
  - linux/amd64
  - linux/arm64
  - darwin/amd64
  - darwin/arm64
  - windows/amd64
  - windows/arm64


builds:
  - id: mason
    dir: .
    main: ./
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags
      - netgo
#    ldflags:
#      - -X main.version={{ .Env.VERSION }}
